### ISSUE TITLE
Scratchpad does not detect that terminal process has ended

### ISSUE THREAD

**Issue by dantefromhell** [hyprland-community/pyprland#13]
When using scratchpads for a Terminal scratchpad as described in https://github.com/hyprland-community/pyprland/wiki/Plugins#scratchpads with `lazy` mode enabled, it is possible to end the terminal process with `CTRL + D` from within the terminal.

When pressing the terminal scratchpad key combo again `pypr` seems to be unaware that the process has ended - nothing happens.
Pressing the keyboard combo for the terminal scratchpad again will restart it. Needing to press the key combo twice is non-intuitive.

**Desired behaviour**
`pypr` restarts the program within a scratchpad in case it was closed on first attempt to open it.

**Possible solution**
It would be great if `pypr` could detect if the program within a scratchpad is still/ not anymore running and restart it accordingly.

**Comment by fdev31** [comment]
This is handled and works fine for me, which terminal app are you running ?

**Comment by dantefromhell** [comment]
wezterm

**Comment by fdev31** [comment]
Can you check if you have the same behavior as I observe:
wezterm doesn't die, so it's stays as a zombie process:
`fab         7442  0.5  0.0      0     0 pts/7    Z+   20:11   0:00 [wezterm-gui] <defunct>`

This is supposed to be managed already, but I'll review this code, thanks for the report!

**Comment by fdev31** [comment]
Can you please check with the latest version ?
The process is zombie but as I said it's handled and I can't reproduce the issue.
The only problem I observe here:

After `^D` has been pressed, pypr believes wezterm is still open and hence "hides" it, while it's already not visible and the user expects it to be shown.
But if you repeat the command it will show as expected (respawning one process).

**Comment by dantefromhell** [comment]
> wezterm doesn't die, so it's stays as a zombie process: 

Indeed I see the same on my system.

> Can you please check with the latest version ?

Happy to.

> After ^D has been pressed, pypr believes wezterm is still open and hence "hides" it, while it's already not visible and the user expects it to be shown.
But if you repeat the command it will show as expected (respawning one process).

I see exactly this behaviour with commit [02de5fb](https://github.com/hyprland-community/pyprland/commit/02de5fbc7643b52369775060e697c75730448dd7)

**Comment by dantefromhell** [comment]
A quick search unearthened hyprland issue https://github.com/hyprwm/Hyprland/issues/2309 which my system is affected by.

I'm wondering if these two might be related and/ or caused by the same issue?

**Comment by fdev31** [comment]
I first thought it was broken. But what you report is then the expected behavior and a minor problem.
One solution would be to detect zombie/dead processes on hide too, not only on show.
I may have a look at it when I have some time.

**Comment by fdev31** [comment]
I pushed a logic change in the last commit.
It's still not perfect IMO, please provide your feedback.
I didn't want to do big changes but I think the "lifecycle" part of the scratchpad logic is not very strong or clear and should be rewritten... I may add it to my todo list but it's really not high priority...

**Comment by fdev31** [comment]
So, I can't find a solution to have a proper (eg: sliding) display on first show for lazy windows.
On the other hand I have a patch which removes support for non-lazy windows which seems to work perfectly regarding auto-respawn of scratches.

I see two options:

- find a way to fix this first display of lazy windows, simplify the code & use this, so there is no "lazy" anymore, it's the default behavior
- there is no way to fix it, and code needs to be refactored so the respawn works well keeping the two modes possible

You may want to check the `onlylazy` branch out: https://github.com/hyprland-community/pyprland/tree/onlylazy

**Comment by dantefromhell** [comment]
> I first thought it was broken.

I went back to re-reading the definition of a zombie process and it's lifecycle. [This article](https://www.geekbits.io/understanding-zombie-processes-in-linux/) was a helpful read.

My python skills are limited, but it seems [scratchpads.py#L193](https://github.com/hyprland-community/pyprland/blob/main/pyprland/plugins/scratchpads.py#L193) is how the program is started if not already active.

After some researching it seems that defunct/ zombie process is the normal behaviour for the way pyprland uses `subprocess.Popen`, as from what I understand the parent program is supposed to care about cleaning up child programs in Linux.

If my understanding is correct, this [StackOverflow article](https://stackoverflow.com/questions/16807603/python-non-blocking-non-defunct-process) should describe the possible solutions. I'm not sure which one is most applicable to modern day Python given the article is ~10years old though.

> I think the "lifecycle" part of the scratchpad logic is not very strong or clear and should be rewritten

If my understanding above is correct, could you create an async callback function that gets triggered when a process ends so it can "clean up" the pyprland internal state?


> It's still not perfect IMO, please provide your feedback.

Yes I can, but it'll have to wait until tomorrow.

**Comment by dantefromhell** [comment]
> So, I can't find a solution to have a proper (eg: sliding) display on first show for lazy windows. On the other hand I have a patch which removes support for non-lazy windows which seems to work perfectly regarding auto-respawn of scratches.
> 
> I see two options:
> 
> * find a way to fix this first display of lazy windows, simplify the code & use this, so there is no "lazy" anymore, it's the default behavior
> * there is no way to fix it, and code needs to be refactored so the respawn works well keeping the two modes possible
> 
> You may want to check the `onlylazy` branch out: https://github.com/hyprland-community/pyprland/tree/onlylazy
> 
> Edit: made further code cleanups & re-introduced non-lazy mode in the "only lazy" branch. May need to test if "class" property matches are working as expected, since I'm not using it. This is the best I can think of, with only first display of a lazy window being incorrect, same scenario for windows which have been closed instead of hidden (again, only first time).
> 
> I believe it's better than the current main branch, waiting for your feedback.

Was this intended to be in issue #18 ?

**Comment by fdev31** [comment]
This problem was highlighted there indeed.
The main technical issue which I don't see a solution for:
There is no way to place the windows instantly...
So the "origin" of the window, is always the previous state...

This can be worked around with non-lazy mode:
The windows are instantly placed when created, semi-prepared to be displayed.

I would need to find a way to instantly move the windows to the "origin" destination and then "non silently" (in hyprland terms) move the window to the target destination.
But I don't see any "silent" version of a command to move windows...

Note: I pushed an update on `onlylazy`, maybe `position` and `size` are broken...
I'm not fully sure it has a sane implementation, it looks like it will try to chain animated commands resulting in strange positions, so I always have to set "position" attribute if I use "size", it's not very convenient... (I lose auto placement).

**Comment by fdev31** [comment]
After a night of sleep, my thoughts:

- main branch is broken
- onlylazy branch is the way to go IMO - hope it doesn't break some features I'm not using (I lack automated testing) - I wish I can merge it into main soon

**Comment by dantefromhell** [comment]
> The windows are instantly placed when created, semi-prepared to be displayed.

Thanks for the explanation, this makes sense.
While I do prefer to launch apps only when they are actually used, I'll might just bite the bullet and stick with the slight overhead.

I've tested commit 5067829 on the `onlylazy` branch, but `ps axu` still shows wezterm as a zombie process.

**Comment by fdev31** [comment]
Ok. Let's recap & refocus :)
The bug was open for "Scratchpad does not detect that terminal process has ended" which wasn't the case, it was just "detected one action later than expected".

Can you confirm the current code implements the behavior you expect, with an early detection?
I'll assume yes & close the bug, if there is an issue please re-open.
